# Generated by Django 3.0.6 on 2020-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adultos',
            field=models.BooleanField(default=False),
        ),
    ]
