# Generated by Django 3.0.6 on 2020-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hilos', '0002_post_adultos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitas',
            field=models.IntegerField(null=True),
        ),
    ]
