# Generated by Django 3.0.6 on 2020-05-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilos', '0003_auto_20200530_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
    ]
