# Generated by Django 3.0.6 on 2020-05-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200529_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Forum_Stats',
        ),
    ]
