# Generated by Django 3.0.6 on 2020-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_forum_stats_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_stats',
            name='usuarios_online',
            field=models.IntegerField(null=True),
        ),
    ]
