# Generated by Django 3.0.6 on 2020-05-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hilos', '0004_remove_post_imagen'),
        ('etiquetas', '0002_usertags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='imagen',
            field=models.ImageField(default='tags/default.jpg', upload_to='tags/'),
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetas.Etiqueta')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hilos.Post')),
            ],
        ),
    ]
