# Generated by Django 3.0.6 on 2020-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200527_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='usuario',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profile_color',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
